In [1]:
import os
os.getcwd() #To get the current working directory

'/Users/pavangodthi/Documents/lSMS-spam-detection-/SMS Spam Detection'

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset 

In [5]:
dataset = pd.read_csv("spam.csv", encoding='latin-1')
dataset.dropna(how="any", inplace=True, axis=1)
dataset.columns = ['label', 'message']
dataset

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Cleaning or pre-processing

In [6]:
#Library to clean the text
import re

#Natural language toolkit library
import nltk

#library used to remove stopwords
nltk.download('stopwords')
from nltk.corpus import stopwords

#Library used for stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()  #creating an object for stemming
data=[]

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pavangodthi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
#Applying for all rows
for i in range(0,5572):
        message=dataset["message"][i]
        
        #replacing punctuations and numbers
        message = re.sub('[^a-zA-Z]', ' ',message)
       
        #convert each word into lower case
        message = message.lower()  
        
        message = message.split()
        
        #apply stemming
        message = [ps.stem(word) for word in message if not word in set(stopwords.words('english'))]
        
        message = ' '.join(message)
        data.append(message)

In [8]:
dataset['label'].replace(['ham','spam'],[0,1],inplace=True)

In [9]:
        
from sklearn.feature_extraction.text import CountVectorizer #for bag of words
cv = CountVectorizer(max_features=100) 
X = cv.fit_transform(data).toarray() #convert into matrix form
y=dataset.iloc[:,0].values 
y

array([0, 0, 1, ..., 0, 0, 0])

# Splitting the dataset into train and test

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [11]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
import pickle
pickle.dump(cv, open("cv.pkl", "wb"))

# Importing the libraries which uses tensorflow as backend

In [16]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [17]:
#Initializing the model
model = Sequential()


#adding input layer
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu', input_dim = 100))

#adding hidden layers
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))
model.add(Dense(output_dim = 8, init = 'uniform', activation = 'relu'))


#Adding output layer
model.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))


/Users/pavangodthi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=100, units=8, kernel_initializer="uniform")`
  
/Users/pavangodthi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  if __name__ == '__main__':
/Users/pavangodthi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/Users/pavangodthi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()

In [18]:
#compiling the model
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
#Training the model
model.fit(X_train,y_train,batch_size=4048,epochs=200)

Epoch 1/200
4457/4457 [==============================] - 0s 9us/step - loss: 0.2597 - accuracy: 0.8696
Epoch 2/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2555 - accuracy: 0.8696
Epoch 3/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2515 - accuracy: 0.8696
Epoch 4/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2476 - accuracy: 0.8696
Epoch 5/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2439 - accuracy: 0.8696
Epoch 6/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2404 - accuracy: 0.8696
Epoch 7/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2369 - accuracy: 0.8696
Epoch 8/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2336 - accuracy: 0.8696
Epoch 9/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.2304 - accuracy: 0.8696
Epoch 10/200
4457/4457 [==============================] - 0s 8us/step - l

4457/4457 [==============================] - 0s 9us/step - loss: 0.1637 - accuracy: 0.8696
Epoch 80/200
4457/4457 [==============================] - 0s 9us/step - loss: 0.1634 - accuracy: 0.8696
Epoch 81/200
4457/4457 [==============================] - 0s 9us/step - loss: 0.1630 - accuracy: 0.8696
Epoch 82/200
4457/4457 [==============================] - 0s 8us/step - loss: 0.1627 - accuracy: 0.8696
Epoch 83/200
4457/4457 [==============================] - 0s 9us/step - loss: 0.1623 - accuracy: 0.8696
Epoch 84/200
4457/4457 [==============================] - 0s 9us/step - loss: 0.1620 - accuracy: 0.8696
Epoch 85/200
4457/4457 [==============================] - 0s 8us/step - loss: 0.1617 - accuracy: 0.8696
Epoch 86/200
4457/4457 [==============================] - 0s 8us/step - loss: 0.1614 - accuracy: 0.8696
Epoch 87/200
4457/4457 [==============================] - 0s 8us/step - loss: 0.1612 - accuracy: 0.8696
Epoch 88/200
4457/4457 [==============================] - 0s 8us/step - loss:

4457/4457 [==============================] - 0s 8us/step - loss: 0.1472 - accuracy: 0.8696
Epoch 158/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.1471 - accuracy: 0.8696
Epoch 159/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.1469 - accuracy: 0.8696
Epoch 160/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.1468 - accuracy: 0.8696
Epoch 161/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.1466 - accuracy: 0.8696
Epoch 162/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.1465 - accuracy: 0.8696
Epoch 163/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.1464 - accuracy: 0.8696
Epoch 164/200
4457/4457 [==============================] - 0s 6us/step - loss: 0.1464 - accuracy: 0.8696
Epoch 165/200
4457/4457 [==============================] - 0s 7us/step - loss: 0.1463 - accuracy: 0.8696
Epoch 166/200
4457/4457 [==============================] - 0s 7us/ste

# Save the model


In [ ]:
model.save('mymodel.h5')